version: '3.7'
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.91.0
    volumes:
      - ./otel-collector.yaml:/etc/otel/collector/config.yaml
    command: [ "--config=/etc/otel/collector/config.yaml" ]
    ports:
      - "55680:55680"
      - "55681:55681"
      - "4317:4317"
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # the jaeger UI
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  grafana:
    image: grafana/grafana:10.0.10
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config:/etc/loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"